# Site settings
title: Microprocessor (Intel 8085, 8086) course offered in IOE Pulchowk
email: mail@maharjansujit.com.np
description: > # this means to ignore newlines until "baseurl:"
  This website is guide for those students who are learning microprocessor. This website contains the lab work of IOE Pulchowk Campus 2nd year 2nd part microprocessor course. I hope its helpful to all who use it.
baseurl: "/microprocessor" # the subpath of your site, e.g. /blog/
url: "https://maharjansujit.com.np" # the base hostname & protocol for your site
twitter_username: frensOfAll
github_username: shubhajeet

# Build settings
markdown: kramdown
